version: 2.1
jobs:
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install wkhtmltopdf
          command:
            sudo apt-get update && sudo apt-get -y install wget xz-utils fontconfig
            postgresql-client openssl build-essential libssl-dev libxrender-dev git-core
            libx11-dev libxext-dev libfontconfig1-dev libfreetype6-dev poppler-utils wkhtmltopdf
      - run:
          name: Set up tox tests
          command: |
            poetry self update
            pip install --upgrade tox
      - restore_cache:
          keys:
            - v1-poetry-deps-{{ checksum "poetry.lock" }}
            - v1-poetry-deps-
      - run:
          name: Run tox tests
          command: tox -e py39
      - save_cache:
          key: v1-poetry-deps-{{ checksum "poetry.lock" }}
          paths:
            - .tox
  integration-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Run the integration test script
          command: .circleci/run_integration_tests.sh
  deploy-dev:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Add build information
          command: .circleci/record_build_info.sh
      - run:
          name: Build docker image
          command: docker build . -t polaris-pdf-api
      - run:
          name: Tag docker image
          command: |
            docker tag polaris-pdf-api ghcr.io/polaris-foundation/polaris-pdf-api:latest
            docker tag polaris-pdf-api ghcr.io/polaris-foundation/polaris-pdf-api:cb-${CIRCLE_BUILD_NUM}
            docker tag polaris-pdf-api ghcr.io/polaris-foundation/polaris-pdf-api:$(git log --pretty=format:'%h' -n 1)
      - run:
          name: Authenticate to GHCR
          command: echo $GHCR_TOKEN | docker login ghcr.io -u jonadaly --password-stdin
      - run:
          name: Push docker image
          command: |
            docker push ghcr.io/polaris-foundation/polaris-pdf-api:latest
            docker push ghcr.io/polaris-foundation/polaris-pdf-api:cb-${CIRCLE_BUILD_NUM}
            docker push ghcr.io/polaris-foundation/polaris-pdf-api:$(git log --pretty=format:'%h' -n 1)
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test:
          context: polaris-foundation
      - integration-test:
          context: polaris-foundation
      - deploy-dev:
          context: polaris-foundation
          requires:
            - test
            - integration-test
          filters:
            branches:
              only:
                - main
